# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'MovieAppMicro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieAppMicro
  pod 'MyLocalPod', :path => './MovieAppMicro/MyLocalPod'

  target 'MovieAppMicroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppMicroUITests' do
    # Pods for testing
  end

end
